### ISSUE TITLE
Run Ball Intake

### ISSUE THREAD

**Issue by npmanos** [itrt4176/rapidreact2022#1]
## Overview

Run the ball intake forward (to intake the ball) and reverse (to reject a wrong color ball).

## Tasks

 - [ ] Resolve CAN ID conflict for Talon SRX
 - [ ] Change Talon in [Intake.java](src/main/java/frc/irontigers/robot/subsystems/Intake.java) to WPI_TalonSRX
 - [ ] Determine output required to consistently intake ball
 - [ ] Test using intake to spit out ball

## Suggested Implementation

- RunIntake(Direction direction, Intake intake) extends Command
  - enum Direction
    - Forward
    - Reverse
    - Stop
  - execute()
    - switch
      - Forward -> set output %
      - Backward -> set reverse output %
      - Stop -> set output to 0
  - isFinished()
    - return false

## Helpful Links

- [WPILib command documentation](https://docs.wpilib.org/en/stable/docs/software/commandbased/commands.html)
- [Java Enum Tutorial](https://www.baeldung.com/a-guide-to-java-enums)
