### ISSUE TITLE
Drive to Pose

### ISSUE THREAD

**Issue by npmanos** [itrt4176/rapidreact2022#7]
## Overview

Follow trajectory to drive robot to a specific position as defined by a Pose2d.

## Tasks

 - [ ] #2 
 - [ ] Characterize drivetrain (SysID)
 - [ ] Add characterized constants to code
 - [ ] Add `driveVolts()` method to drive subsystem
 - [ ] Create trajectory config
 - [ ] Implement RamseteCommand

## Suggested Implementation

Follow tutorials in Helpful Links below

## Helpful Links

[Characterization tutorial](https://docs.wpilib.org/en/stable/docs/software/pathplanning/system-identification/index.html)
[Trajectory tutorial](https://docs.wpilib.org/en/stable/docs/software/pathplanning/system-identification/index.html)

## Notes

Only additions to the drive subsystem required should be the `driveVolts` method. Everything else should already be provided by `MecanumDriveSubsystem` once #2 is complete.
