### ISSUE TITLE
Auto Driving

### ISSUE THREAD

**Issue by npmanos** [itrt4176/rapidreact2022#8]
## Overview

Make the robot drive manually and autonomously.

## Tasks

 - [ ] #7
 - [ ] Determine possible starting positions
 - [ ] Create PathWeaver trajectories for each starting position
 - [ ] Add chooser for driver to select starting position/correct trajectory

## Helpful Links

[PathWeaver tutorial](https://docs.wpilib.org/en/stable/docs/software/pathplanning/pathweaver/index.html)
